# Makefile for millionaire.cpp game
# by Kevin Vo

# compiler: gcc for C program define as g


# build an executable named main from millionaire.cpp
all: millionaire.cpp
	g++ millionaire.cpp -o millionaire
	
clean:
	rm millionaire
